[book]
title = "Networking for Non-Network Engineers"
description = "A practical guide to Linux networking for DevOps, Platform, SRE, and Backend engineers."
authors = ["kaveh moradian"]
language = "en"

[output.html]
preferred-dark-theme = "navy"
no-section-label = true
git-repository-url = "https://github.com/kavehmoradian/Networking-for-Non-Network-Engineers.git"

[output.html.search]
enable = true
limit-results = 20
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true

[output.html.fold]
enable = true
level = 1
